"""empty message

Revision ID: 675df0087c6d
Revises: 
Create Date: 2022-08-01 17:38:33.382474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675df0087c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('choices', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('x', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choices')
    # ### end Alembic commands ###
